#!/usr/bin/env bash
# Install nginx on your web-01 server
#!/usr/bin/env bash
# Configuring a server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
